


local zhipai_config = {}


zhipai_config.poker_config = {
	[1]  	= "imagezhipai/poker/meihuaa.png",
	[2]  	= "imagezhipai/poker/meihua2.png",
	[3]  	= "imagezhipai/poker/meihua3.png",
	[4] 	= "imagezhipai/poker/meihua4.png",
	[5]  	= "imagezhipai/poker/meihua5.png",
	[6]  	= "imagezhipai/poker/meihua6.png",
	[7]  	= "imagezhipai/poker/meihua7.png",
	[8]  	= "imagezhipai/poker/meihua8.png",
	[9]  	= "imagezhipai/poker/meihua9.png",
	[10]  	= "imagezhipai/poker/meihua10.png",
	[11]  	= "imagezhipai/poker/meihuaj.png",
	[12]    = "imagezhipai/poker/meihuaq.png",
	[13]    = "imagezhipai/poker/meihuak.png",

	[14]     = "imagezhipai/poker/fangkuaia.png",
	[15]     = "imagezhipai/poker/fangkuai2.png",
	[16]     = "imagezhipai/poker/fangkuai3.png",
	[17]     = "imagezhipai/poker/fangkuai4.png",
	[18]     = "imagezhipai/poker/fangkuai5.png",
	[19]     = "imagezhipai/poker/fangkuai6.png",
	[20]     = "imagezhipai/poker/fangkuai7.png",
	[21]     = "imagezhipai/poker/fangkuai8.png",
	[22]     = "imagezhipai/poker/fangkuai9.png",
	[23]     = "imagezhipai/poker/fangkuai10.png",
	[24]     = "imagezhipai/poker/fangkuaij.png",
	[25]     = "imagezhipai/poker/fangkuaiq.png",
	[26]     = "imagezhipai/poker/fangkuaik.png",

	[27]     = "imagezhipai/poker/heitao2.png",
	[28]     = "imagezhipai/poker/heitao3.png",
	[29]     = "imagezhipai/poker/heitao4.png",
	[30]     = "imagezhipai/poker/heitao5.png",
	[31]     = "imagezhipai/poker/heitao6.png",
	[32]     = "imagezhipai/poker/heitao7.png",
	[33]     = "imagezhipai/poker/heitao8.png",
	[34]     = "imagezhipai/poker/heitao9.png",
	[35]     = "imagezhipai/poker/heitao10.png",
	[36]     = "imagezhipai/poker/heitaoj.png",
	[37]     = "imagezhipai/poker/heitaok.png",
	[38]     = "imagezhipai/poker/heitaoq.png",
	[39]     = "imagezhipai/poker/heitaoa.png",

	[40]     = "imagezhipai/poker/hongxin2.png",
	[41]     = "imagezhipai/poker/hongxin3.png",
	[42]     = "imagezhipai/poker/hongxin4.png",
	[43]     = "imagezhipai/poker/hongxin5.png",
	[44]     = "imagezhipai/poker/hongxin6.png",
	[45]     = "imagezhipai/poker/hongxin7.png",
	[46]     = "imagezhipai/poker/hongxin8.png",
	[47]     = "imagezhipai/poker/hongxin9.png",
	[48]     = "imagezhipai/poker/hongxin10.png",
	[49]     = "imagezhipai/poker/hongxina.png",
	[50]     = "imagezhipai/poker/hongxinj.png",
	[51]     = "imagezhipai/poker/hongxink.png",
	[52]     = "imagezhipai/poker/hongxinq.png",
}

zhipai_config.num_config = {
	[1]		 = { 1,11 },
	[2]		 = { 2 },
	[3]		 = { 3 },
	[4]		 = { 4 },
	[5]		 = { 5 },
	[6]		 = { 6 },
	[7]		 = { 7 },
	[8]		 = { 8 },
	[9]		 = { 9 },
	[10]     = { 10 },
	[11]     = { 10 },
	[12]     = { 10 },
	[13]     = { 10 },

	[14]     = { 1,11 },
	[15]     = { 2 },
	[16]     = { 3 },
	[17]     = { 4 },
	[18]     = { 5 },
	[19]     = { 6 },
	[20]     = { 7 },
	[21]     = { 8 },
	[22]     = { 9 },
	[23]     = { 10 },
	[24]     = { 10 },
	[25]     = { 10 },
	[26]     = { 10 },

	[27]     = { 2 },
	[28]     = { 3 },
	[29]     = { 4 },
	[30]     = { 5 },
	[31]     = { 6 },
	[32]     = { 7 },
	[33]     = { 8 },
	[34]     = { 9 },
	[35]     = { 10 },
	[36]     = { 10 },
	[37]     = { 10 },
	[38]     = { 10 },
	[39]     = { 1,11 },

	[40]     = { 2 },
	[41]     = { 3 },
	[42]     = { 4 },
	[43]     = { 5 },
	[44]     = { 6 },
	[45]     = { 7 },
	[46]     = { 8 },
	[47]     = { 9 },
	[48]     = { 10 },
	[49]     = { 1,11 },
	[50]     = { 10 },
	[51]     = { 10 },
	[52]     = { 10 },
}

rawset(_G,"zhipai_config",zhipai_config)